# Docker Volumes

Docker containerの中で作成されるファイルはコンテナ破棄の時に削除される。論文執筆や発表の準備の時はまとめた結果を保存したい場合がある。コンテナの中で作成された一部のファイルを、コンテナ外の環境とつながっているフォルダーに保存できればコンテナを破棄してもそのファイルが残って便利だろう。このセクションではその「外と繋がったフォルダー」の作り方を紹介する。

自分のパソコンに次のようなフォルダー構造があった場合を考えてみよう：

```
.
├── my-project
│   ├── Dockerfile
│   ├── analyze_data.py
│   └── clean_datga.py
└── results
    └── figure_1.png
```
自分の`/home/`フォルダーに **my-project**と**results**という二つのフォルダーがある。Dockerfileは`my-project`の中にあるため、そのフォルダーの中から`docker build --tag my-research-image`を実行しても **results**の内容がDocker Imageの中にコピーされない。コンテナの中で得られたデータ分析の結果を**results**に保存したい場合はそのフォルダーとコンテナの中のフォルダーとの橋を作る必要がある。その時は`docker run`の`-v`オプションが使われる。この例では：
```
docker run -v /home/results:/home/rstudio/results my-research-image
```
というようなコマンドを使えばDocker volumeを作成することができる。この例ではそのvolumeはコンテナの外の`/home/results`というフォルダーをコンテナの中にある`/home/rstudio/results`と繋いでいる。パソコンの `/home/results`フォルダーに保存されたファイルはコンテナの中の`/home/rstudio/results`からアクセスできて、逆にコンテナの中でそのロケーションに置かれるファイルは自分のパソコンの`/home/results`というフォルダーからアクセスできる。コンテナが破棄されてもvolumeのファイルは削除されない。


Docker volumesの使い方が複数あるためvolumesの [公式ガイド](https://docs.docker.jp/engine/userguide/dockervolumes.html)を確認しましょう。


