# セキュリティ

Docker is a very convenient and powerful tool, but as any software out there you must use it with care. In this section I discuss some topics you should always have in mind when using Docker on your research.

## Managing Data

Docker images are files. Consequently, when you share a Docker image or upload it to a public repository such as Docker Hub, you must have in mind that you are sharing data. There's always some data that you don't want to share, whether because it's sensitive (license keys, credentials, etc.), or because the terms of usage of the data do not allow it. Here are some tips that can help you avoid unwanted data leaks.

For example, consider the following directory structure:

```
├── .env
├── Dockerfile
├── code
│   ├── estimation.R
│   └── read_data.R
└── data
    ├── survey_2011.csv
    ├── survey_2012.csv
    └── survey_2013.csv
```

If you run `docker build .` in this directory, the `csv` files within the `data` directory may be copied into the resulting docker image if the **ADD** directive is used in the *Dockerfile*. If you share that image with someone else, they would have access to the data. Also the `.env` file may contain license keys and other credentials which you do not want to share. You have a few options to avoid unexpected data leaks:

### Use a `.dockerignore` file
Just like `.gitignore` files let you define files and directories that should not be subject of version controll by git, `.dockerignore` files let you specify files which should not be included inside docker images when using the **ADD** directive. Just include a `.dockerignore` file in the same directory as the Dockerfile. Its contents should include the path to the files you want to exclude. The format of the file is similar to that of `.gitignore` files.

### Use volumes

The file structure in the previous example is inconvenient. Not just because there's the risk of including unwanted data in a docker image, but also because you run the risk of committing those files to your version control system, such as git.

It is a better idea to put the contents of the `data` directory in a secured database. But if you must keep the files in your hard disk for whatever reason, you should place them in a location outside the project's folder and make them available to the code within the container using docker volumes.


## Using External Docker Images

Docker containers are extremely safe by default. However, it is always a good idea to prefer using verified images when you download them from Docker Hub, and to always check the content of the Dockerfiles you use to build images on your computer.

You can read about the security of Docker containers [here](https://docs.docker.jp/engine/security/security.html).


